### ISSUE TITLE
打扰一下，我使用Chanzhaoyu/chatgpt-web这个前端项目，发现回答完问题后不会自动停止响应。

### ISSUE THREAD

**Issue by xiaosaaaa** [aurorax-neo/coze-chat-proxy#5]
![捕获](https://github.com/aurorax-neo/coze-chat-proxy/assets/115446601/78aff69f-f444-4748-8f2c-ba79fd4dd434)

**Comment by aurorax-neo** [comment]
> ![捕获](https://private-user-images.githubusercontent.com/115446601/300224731-78aff69f-f444-4748-8f2c-ba79fd4dd434.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDY3NjQsIm5iZiI6MTcwNjQwNjQ2NCwicGF0aCI6Ii8xMTU0NDY2MDEvMzAwMjI0NzMxLTc4YWZmNjlmLWY0NDQtNDc0OC04ZjJjLWJhNzlmZDRkZDQzNC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwMTQ3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTJlMGY1NDNhYjIzOWUyMTVhNDBkZGE1ZmJmMjFhMTdkZWMzYjM5OThkNDZlYWRiNDFkNmU4NDAxNzc1YjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pdgqe4HRuR_prKW34BQ0mS8aMiW6WxrWi36gsm870Is)

尝试修复了一下，我没有Chanzhaoyu/chatgpt-web，请重新拉取一下再试试

**Comment by xiaosaaaa** [comment]
完美解决，十分感谢。
还有个问题请教一下，就是怎么样能重置对话呢？在原网页上有个Clear all能重置，在discord里或者其他项目里有命令能重置吗？

**Comment by aurorax-neo** [comment]
> 完美解决，十分感谢。
> 
> 还有个问题请教一下，就是怎么样能重置对话呢？在原网页上有个Clear all能重置，在discord里或者其他项目里有命令能重置吗？

请问原网页指的是哪个网页？

**Comment by xiaosaaaa** [comment]
coze的页面上可以直接聊天，有个小刷子可以重置对话。

**Comment by aurorax-neo** [comment]
> coze的页面上可以直接聊天，有个小刷子可以重置对话。

这是直接走的discord机器人应该与原网页不同，具体我也不太了解

**Comment by xiaosaaaa** [comment]
> > coze的页面上可以直接聊天，有个小刷子可以重置对话。
> 
> 这是直接走的discord机器人应该与原网页不同，具体我也不太了解

好的，我再研究研究。
