### ISSUE TITLE
coze 机器人会回复用户消息，但不会回复代理机器人的消息？

### ISSUE THREAD

**Issue by mwcodefun** [aurorax-neo/coze-chat-proxy#7]
![image](https://github.com/aurorax-neo/coze-chat-proxy/assets/92509909/4f39f2ab-f231-4533-b67a-385c822d74be)

配置应该没有问题，是现在coze不支持了吗？

**Comment by aurorax-neo** [comment]
> ![image](https://private-user-images.githubusercontent.com/92509909/318015660-4f39f2ab-f231-4533-b67a-385c822d74be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjE3MjAsIm5iZiI6MTcxMTg2MTQyMCwicGF0aCI6Ii85MjUwOTkwOS8zMTgwMTU2NjAtNGYzOWYyYWItZjIzMS00NTMzLWI2N2EtMzg1YzgyMmQ3NGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA1MDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMWVjMDYzZTlkYmQ0NDlhZDdkYWEyOTc2YmI1OGI5YWZlYTllNjg4NDFhZmQwMGQwY2NjNGU2YTliYjRkN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zMjfltayKPhpGQcbBSUTm_ald4VClEwMup-H86HDlVg)
> 
> 配置应该没有问题，是现在coze不支持了吗？

dis检测了机器人和机器人对话 我没有去修复
